std = "roblox"

[config]
# Allow for `_G.__DEV__` (etc) with packages like React-lua
global_usage = { ignore_pattern = "^__" }

[rules]
shadowing = "allow"
global_usage = "allow"
undefined_variable = "allow"
unused_variable = "allow"
unscoped_variables = "allow"
