std = "roblox"
exclude = ["**/.typedefs/**", "*.spec.lua", "**/*.mdc", "**/Packages/**"]

[config]
# Allow for `_G.__DEV__` (etc) with packages like React-lua
global_usage = { ignore_pattern = "^__" }

[rules]
shadowing = "allow"
global_usage = "allow"
undefined_variable = "allow"
unscoped_variables = "allow"
incorrect_standard_library_use = "allow"
multiple_statements = "allow"
unused_variable = "allow"
